### ISSUE TITLE
[TODO] 앞으로 작업해야할 것

### ISSUE THREAD

**Issue by WooBinHam** [YOGIZOGI/YOGIZOGI-Android#10]
- [ ] Toast 메세지 띄우는 부분 BaseFragment에 작성해서 불필요한 코드 줄이기
- [ ] Text Style 세분화 해서 만들어 적용하기
- [x] 회원가입 하는 부분에 Lottie 적용하기
